/*
 * ProxyListDlg.java
 *
 * Created on 27. November 2008, 12:25
 */

package dimm.home.mailproxyclient;

import dimm.home.mailproxyclient.Utilities.ParseToken;
import java.awt.Color;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.table.AbstractTableModel;



class ProxyListModel extends AbstractTableModel
{
    ArrayList<ProxyEntry> proxy_list;
    String col_names[] = {"Protokoll", "LocalPort", "Host", "RemotePort" };
    Class col_classes[] = {String.class, Integer.class, String.class, Integer.class };

    @Override
    public Class<?> getColumnClass(int columnIndex)
    {
        return super.getColumnClass(columnIndex);
    }

    @Override
    public String getColumnName(int column)
    {
        return col_names[column];
    }
    
    ProxyListModel( ArrayList<ProxyEntry> _proxy_list )
    {
        proxy_list = _proxy_list;
    }

    public int getRowCount()
    {
        return proxy_list.size();
    }

    public int getColumnCount()
    {
        return col_names.length;
    }

    public Object getValueAt(int rowIndex, int columnIndex)
    {
        ProxyEntry pe = proxy_list.get(rowIndex);
        switch ( columnIndex )
        {
            case 0: return pe.getProtokoll();
            case 1: return pe.getLocalPort();
            case 2: return pe.getHost();
            case 3: return pe.getRemotePort();
            
        }
        return "?";
    }
}

/**
 
 @author  Administrator
 */
public class ProxyListDlg extends javax.swing.JDialog
{
    MainFrame parent;
    ProxyListModel model;
    ArrayList<ProxyEntry> proxy_list;
    
    /** Creates new form ProxyListDlg */
    public ProxyListDlg(MainFrame parent)
    {
        super(parent, true);
        this.parent = parent;
        this.proxy_list = new ArrayList<ProxyEntry>();
        
        initComponents();
        
        read_params();
                
        model = new ProxyListModel(proxy_list);
        TB_PROXYLIST.setModel(model);
        
        TB_PROXYLIST.setShowVerticalLines(false);
        TB_PROXYLIST.setGridColor(Color.LIGHT_GRAY);
        TB_PROXYLIST.getColumnModel().getColumn(0).setPreferredWidth(50);
        TB_PROXYLIST.getColumnModel().getColumn(1).setPreferredWidth(50);
        TB_PROXYLIST.getColumnModel().getColumn(2).setPreferredWidth(150);
        TB_PROXYLIST.getColumnModel().getColumn(3).setPreferredWidth(50);
        
        
        
        
    }
    void read_params()
    {
        if (parent.send_cmd("PROXYLIST CMD:GET"))
        {
            
            proxy_list.clear();
            
            StringTokenizer sto = new StringTokenizer( parent.get_answer(), "\n\r" );
            while (sto.hasMoreTokens())
            {
                String line = sto.nextToken();
                if (line.length() == 0)
                    continue;
                if (line.charAt(0) == '#')
                    continue;

                try
                {
                    StringTokenizer stl = new StringTokenizer(line, "\t");
                    String prot = stl.nextToken();
                    int lport = Integer.parseInt(stl.nextToken());
                    String host = stl.nextToken();
                    int rport = Integer.parseInt(stl.nextToken());

                    ProxyEntry pe = new ProxyEntry(host, lport, rport, 0, prot);

                    proxy_list.add(pe);

                }
                catch (Exception exception)
                {
                    parent.errm_ok("Fehler beim Einlesen der Proxyliste!");
                }
            }                
        }
    }
    
    boolean write_params()
    {
        StringBuffer sb = new StringBuffer("PROXYLIST CMD:SET ");
        
        for (int i = 0; i < proxy_list.size(); i++)
        {
            ProxyEntry proxyEntry = proxy_list.get(i);
            
            sb.append("LINE");
            sb.append(i);
            sb.append(":'");
            sb.append(proxyEntry.getProtokoll());
            sb.append("\t");
            sb.append(proxyEntry.getLocalPort());
            sb.append("\t");
            sb.append(proxyEntry.getHost());
            sb.append("\t");
            sb.append(proxyEntry.getRemotePort());
            sb.append("'\n");
        }

        return parent.send_cmd(sb.toString());
    }
        
            
    /** This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB_PROXYLIST = new javax.swing.JTable();
        BT_EDIT = new javax.swing.JButton();
        BT_NEW = new javax.swing.JButton();
        BT_DEL = new javax.swing.JButton();
        BT_ABORT = new javax.swing.JButton();
        BT_OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TB_PROXYLIST.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TB_PROXYLIST.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                TB_PROXYLISTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TB_PROXYLIST);

        BT_EDIT.setText("Bearbeiten");
        BT_EDIT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BT_EDITActionPerformed(evt);
            }
        });

        BT_NEW.setText("Neu");
        BT_NEW.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BT_NEWActionPerformed(evt);
            }
        });

        BT_DEL.setText("Löschen");
        BT_DEL.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BT_DELActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BT_DEL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(BT_NEW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT_EDIT)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BT_DEL, BT_EDIT, BT_NEW});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_EDIT)
                    .addComponent(BT_NEW)
                    .addComponent(BT_DEL))
                .addContainerGap())
        );

        BT_ABORT.setText("Abbruch");
        BT_ABORT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BT_ABORTActionPerformed(evt);
            }
        });

        BT_OK.setText("Setzen");
        BT_OK.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BT_OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BT_ABORT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT_OK)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BT_ABORT, BT_OK});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_OK)
                    .addComponent(BT_ABORT))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_ABORTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_ABORTActionPerformed
    {//GEN-HEADEREND:event_BT_ABORTActionPerformed
        // TODO Ihre Ereignisbehandlung hier einf�gen:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BT_ABORTActionPerformed

    private void BT_OKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_OKActionPerformed
    {//GEN-HEADEREND:event_BT_OKActionPerformed
        // TODO Ihre Ereignisbehandlung hier einf�gen:
        
        if (!parent.check_logged_in())
        {
            return;
        }
        
        if (write_params())
        {
            this.setVisible(false);
            this.dispose();
        }
        else
        {
            parent.errm_ok( "Die Proxyliste konnt nicht gesetzt werden");
        }
    }//GEN-LAST:event_BT_OKActionPerformed

    private void BT_EDITActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_EDITActionPerformed
    {//GEN-HEADEREND:event_BT_EDITActionPerformed
        // TODO add your handling code here:
        int idx = TB_PROXYLIST.getSelectedRow();
        ProxyEntry pe = proxy_list.get( idx );
        EditProxyDlg dlg = new EditProxyDlg( parent, pe );
        dlg.setLocation( this.getLocationOnScreen().x + 30, this.getLocationOnScreen().y + 30);
        dlg.setVisible(true);
        
        pe = dlg.get_proxy_entry();
        if (pe != null)
            proxy_list.set( idx, pe);
        
        model.fireTableDataChanged();
        
    }//GEN-LAST:event_BT_EDITActionPerformed

    private void BT_DELActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_DELActionPerformed
    {//GEN-HEADEREND:event_BT_DELActionPerformed

        int idx = TB_PROXYLIST.getSelectedRow();
        
        proxy_list.remove(idx);
        
        model.fireTableDataChanged();
        
    }//GEN-LAST:event_BT_DELActionPerformed

    private void BT_NEWActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_NEWActionPerformed
    {//GEN-HEADEREND:event_BT_NEWActionPerformed
        // TODO add your handling code here:
        ProxyEntry pe = new ProxyEntry("", 110, 110, 0, "POP3");
        EditProxyDlg dlg = new EditProxyDlg( parent, pe );
        dlg.setLocation( this.getLocationOnScreen().x + 30, this.getLocationOnScreen().y + 30);
        dlg.setVisible(true);
        
        pe = dlg.get_proxy_entry();
        
        if (pe != null)
            proxy_list.add( pe );
        
        model.fireTableDataChanged();
        
    }//GEN-LAST:event_BT_NEWActionPerformed

    private void TB_PROXYLISTMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_TB_PROXYLISTMouseClicked
    {//GEN-HEADEREND:event_TB_PROXYLISTMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2)
        {
            BT_EDITActionPerformed( null );
        }
    }//GEN-LAST:event_TB_PROXYLISTMouseClicked
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_ABORT;
    private javax.swing.JButton BT_DEL;
    private javax.swing.JButton BT_EDIT;
    private javax.swing.JButton BT_NEW;
    private javax.swing.JButton BT_OK;
    private javax.swing.JTable TB_PROXYLIST;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
