package dimm.home.mailproxyclient;

/*
 * RestartDlg.java
 *
 * Created on 15. Oktober 2007, 00:24
 */



/**
 *
 * @author  Administrator
 */
public class RestartDlg extends javax.swing.JDialog
{
    MainFrame parent;
    
    /** Creates new form RestartDlg */
    public RestartDlg(MainFrame _parent)
    {
        super(_parent, true);
        parent = _parent;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Erzeugter Quelltext ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        BT_OK = new javax.swing.JButton();
        BT_ABORT = new javax.swing.JButton();
        CB_LAST_VERSION = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Programm neu starten");
        BT_OK.setText("Neustart");
        BT_OK.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BT_OKActionPerformed(evt);
            }
        });

        BT_ABORT.setText("Abbruch");
        BT_ABORT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BT_ABORTActionPerformed(evt);
            }
        });

        CB_LAST_VERSION.setText("Vorherige Version verwenden");
        CB_LAST_VERSION.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        CB_LAST_VERSION.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .add(BT_ABORT)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(BT_OK)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(CB_LAST_VERSION)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {BT_ABORT, BT_OK}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(CB_LAST_VERSION)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 21, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(BT_OK)
                    .add(BT_ABORT))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_ABORTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_ABORTActionPerformed
    {//GEN-HEADEREND:event_BT_ABORTActionPerformed
// TODO Ihre Ereignisbehandlung hier einf�gen:
        this.setVisible( false );
        this.dispose();
    }//GEN-LAST:event_BT_ABORTActionPerformed

    private void BT_OKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_OKActionPerformed
    {//GEN-HEADEREND:event_BT_OKActionPerformed
// TODO Ihre Ereignisbehandlung hier einf�gen:
        if (parent.errm_ok_cancel("Wollen Sie das Programm wirklich neustarten?"))
        {
            this.setVisible( false );
            this.dispose();
            parent.send_cmd("RESTART LV:" + (this.CB_LAST_VERSION.isSelected() ? "1" : "0" ) );
        }
    }//GEN-LAST:event_BT_OKActionPerformed
    
    
    // Variablendeklaration - nicht modifizieren//GEN-BEGIN:variables
    private javax.swing.JButton BT_ABORT;
    private javax.swing.JButton BT_OK;
    private javax.swing.JCheckBox CB_LAST_VERSION;
    // Ende der Variablendeklaration//GEN-END:variables
    
}
