package dimm.home.mailproxyclient;

/*
 * ShellDlg.java
 *
 * Created on 14. Oktober 2007, 21:44
 */



import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JTextArea;

/**
 *
 * @author  Administrator
 */
class TightTextArea extends JTextArea
{
    int h;
    public TightTextArea(int _h)
    {
        super();
        h = _h;
    }
    protected int getRowHeight()
    {
        return h;
    }
}


public class ShellDlg extends javax.swing.JDialog
{
    MainFrame parent;
    ArrayList hist_array;
    JTextArea LOG_TEXT;
    
    int hist_pos = 0;
    
    
    /** Creates new form ShellDlg */
    public ShellDlg(MainFrame _parent)
    {
        super(_parent, true);
        parent = _parent;
        initComponents();
        
        hist_array =new ArrayList();
        
        do_inits();
        
    }
    
    private void do_inits()
    {
        LOG_TEXT = new TightTextArea/*JTextArea*/(7);
        LOG_TEXT.setEditable(false);
        LOG_TEXT.setTabSize(4);
        LOG_TEXT.setAutoscrolls(false);
        LOG_TEXT.setFont( TXT_CMD.getFont() );
        LOG_TEXT.setForeground(TXT_CMD.getForeground());
        LOG_TEXT.setBackground(TXT_CMD.getBackground());
        //LOG_TEXT.setFocusable( false );
        
        SCROLL_PANE.setViewportView(LOG_TEXT);
                        
        pack();
        
        
        this.getRootPane().setDefaultButton(BT_OK);
                
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        TXT_CMD = new javax.swing.JTextField();
        BT_OK = new javax.swing.JButton();
        SCROLL_PANE = new javax.swing.JScrollPane();
        TXT_TEXT = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BettyMail Terminal");

        jLabel1.setText("Befehl");

        TXT_CMD.setBackground(new java.awt.Color(0, 0, 0));
        TXT_CMD.setFont(new java.awt.Font("Courier New", 0, 12));
        TXT_CMD.setForeground(new java.awt.Color(51, 204, 0));
        TXT_CMD.setCaretColor(new java.awt.Color(51, 204, 0));
        TXT_CMD.setMargin(new java.awt.Insets(4, 4, 4, 4));
        TXT_CMD.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TXT_CMDActionPerformed(evt);
            }
        });
        TXT_CMD.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                TXT_CMDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                TXT_CMDKeyTyped(evt);
            }
        });

        BT_OK.setText("Schliessen");
        BT_OK.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BT_OKActionPerformed(evt);
            }
        });

        TXT_TEXT.setBackground(new java.awt.Color(0, 0, 0));
        TXT_TEXT.setColumns(20);
        TXT_TEXT.setEditable(false);
        TXT_TEXT.setFont(new java.awt.Font("Courier New", 0, 13));
        TXT_TEXT.setForeground(new java.awt.Color(51, 204, 0));
        TXT_TEXT.setRows(5);
        TXT_TEXT.setText("fspafjdiwufoöiauzfuwehiuahruipefg");
        TXT_TEXT.setMargin(new java.awt.Insets(4, 4, 4, 4));
        SCROLL_PANE.setViewportView(TXT_TEXT);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(SCROLL_PANE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(TXT_CMD, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, BT_OK))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(SCROLL_PANE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(TXT_CMD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(BT_OK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_CMDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TXT_CMDActionPerformed
    {//GEN-HEADEREND:event_TXT_CMDActionPerformed
// TODO Ihre Ereignisbehandlung hier einf�gen:
        String cmd = TXT_CMD.getText();
        
        if (cmd.length() > 0)
        {
            parent.send_cmd("SHELLCMD CMD:'" + cmd + "'" );
            LOG_TEXT.append( "# " + cmd + "\n" );
            LOG_TEXT.append(parent.get_answer() + "\n" );
            LOG_TEXT.setCaretPosition( LOG_TEXT.getText().length() );
            hist_array.add( cmd );
            hist_pos = 0;
            TXT_CMD.setText("");
        }
        else
        {
            LOG_TEXT.append("\n" );
        }
        
    }//GEN-LAST:event_TXT_CMDActionPerformed

    private void TXT_CMDKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_TXT_CMDKeyPressed
    {//GEN-HEADEREND:event_TXT_CMDKeyPressed
// TODO Ihre Ereignisbehandlung hier einf�gen:
        TXT_CMDKeyTyped( evt );
    }//GEN-LAST:event_TXT_CMDKeyPressed

    private void TXT_CMDKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_TXT_CMDKeyTyped
    {//GEN-HEADEREND:event_TXT_CMDKeyTyped
// TODO Ihre Ereignisbehandlung hier einf�gen:
        if (evt.getKeyCode() == evt.VK_UP)
        {
            if (hist_array.size() > hist_pos)
            {
                 hist_pos++;
                 String h_cmd = hist_array.get( hist_array.size() - hist_pos ).toString();
                 TXT_CMD.setText( h_cmd );
            }
        }
        if (evt.getKeyCode() == evt.VK_DOWN)
        {
            if (hist_pos > 0)
            {
                hist_pos--;
                if (hist_pos > 0)
                {
                     String h_cmd = hist_array.get( hist_array.size() - hist_pos ).toString();
                     TXT_CMD.setText( h_cmd );
                }
                else
                {
                    TXT_CMD.setText( "" );                
                }                                  
            }
            else
                TXT_CMD.setText( "" );                
        }
        
    }//GEN-LAST:event_TXT_CMDKeyTyped

    private void BT_OKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_OKActionPerformed
    {//GEN-HEADEREND:event_BT_OKActionPerformed
// TODO Ihre Ereignisbehandlung hier einf�gen:
        setVisible(false);
        dispose();
        
        
    }//GEN-LAST:event_BT_OKActionPerformed
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_OK;
    private javax.swing.JScrollPane SCROLL_PANE;
    private javax.swing.JTextField TXT_CMD;
    private javax.swing.JTextArea TXT_TEXT;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
