package dimm.home.mailproxyclient;

/*
 * StationIDDlg.java
 *
 * Created on 9. Oktober 2007, 15:16
 */



/**
 *
 * @author  Administrator
 */
public class StationIDDlg extends javax.swing.JDialog
{
    MainFrame parent;
    
    /** Creates new form StationIDDlg */
    public StationIDDlg(MainFrame _parent)
    {
        super(_parent, true);
        parent = _parent;
        initComponents();
        
        String cmd = "GETSETOPTION CMD:GETLONG NAME:StationID";
        if (parent.send_cmd( cmd ))
        {
            try
            {
                int id = Integer.parseInt( parent.get_answer() );
                SP_ID.setValue(new Integer( id ));
            }
            catch (Exception exc)
            {}
                
        }

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Erzeugter Quelltext ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jLabel1 = new javax.swing.JLabel();
        SP_ID = new javax.swing.JSpinner();
        BT_ABORT = new javax.swing.JButton();
        BT_OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stations-ID festsetzen");
        jLabel1.setText("Neue Stations-ID:");

        BT_ABORT.setText("Abbruch");
        BT_ABORT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BT_ABORTActionPerformed(evt);
            }
        });

        BT_OK.setText("OK");
        BT_OK.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BT_OKActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(SP_ID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(BT_ABORT))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, BT_OK))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {BT_ABORT, BT_OK}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(SP_ID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(BT_ABORT))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(BT_OK)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_OKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_OKActionPerformed
    {//GEN-HEADEREND:event_BT_OKActionPerformed
// TODO Ihre Ereignisbehandlung hier einf�gen:
        if (set_station_id())
        {
            parent.run_scan();
            setVisible(false);
        }
    }//GEN-LAST:event_BT_OKActionPerformed

    private void BT_ABORTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_ABORTActionPerformed
    {//GEN-HEADEREND:event_BT_ABORTActionPerformed
// TODO Ihre Ereignisbehandlung hier einf�gen:
        this.setVisible(false);
    }//GEN-LAST:event_BT_ABORTActionPerformed
    
    /**
     * @param args the command line arguments
     */


    private boolean set_station_id()
    {
        int id =  ((Integer)SP_ID.getValue()).intValue();
        if (id <= 0)
        {
            parent.errm_ok( "Bitte geben Sie eine gueltige Stations-ID an ( 1...)");
            return false;
        }
        
        StationEntry ste = parent.get_selected_box();
        if (ste.get_id() == id)
        {
            if (!parent.errm_ok_cancel("Der " + Main.SERVERAPP + " hat bereits diese Stations-ID! Wollen Sie fortfahren?"))
                return false;
        }
            
        for (int i = 0; i < parent.get_station_entries(); i++)
        {
            ste = parent.get_station( i );
            if (ste.get_id() == id)
            {
                if (!parent.errm_ok_cancel("Diese Stations-ID ist bereits vergeben!!! Wollen Sie wirklich fortfahren?"))
                    return false;
            }
        }
                
        
        
        String cmd = "SETSTATION ID:" + id; 
        if (!parent.send_cmd( cmd ))
        {
            parent.errm_ok("Stations-ID setzen ist fehlgeschlagen: " + parent.get_answer_err_text());
            return false;
        }
        /*
        cmd = "GETSETOPTION CMD:GETLONG NAME:StationID"; 
        if (!parent.send_cmd( cmd ))
        {
            parent.errm_ok("Stations-ID lesen ist fehlgeschlagen: " + parent.get_answer_err_text());
            return false;
        }
        
        String id_str = parent.get_answer();
        try
        {
            int new_id = Integer.parseInt( id_str);
            if (new_id != id)
            {
                parent.errm_ok("Die neue Stations-ID wurde von der Box nicht angenommen" );
                return false;
            }
        }
        catch (Exception exc)
        {
            exc.printStackTrace();
        }
          */
        return true;
    }
    
    // Variablendeklaration - nicht modifizieren//GEN-BEGIN:variables
    private javax.swing.JButton BT_ABORT;
    private javax.swing.JButton BT_OK;
    private javax.swing.JSpinner SP_ID;
    private javax.swing.JLabel jLabel1;
    // Ende der Variablendeklaration//GEN-END:variables
    
}
