package dimm.home.mailproxyclient;

/*
 * TargetPathDlg.java
 *
 * Created on 20. Oktober 2007, 16:19
 */



/**
 *
 * @author  Administrator
 */
public class TargetPathDlg extends javax.swing.JDialog
{
    boolean okay = false;
    
    /** Creates new form TargetPathDlg */
    public TargetPathDlg(MainFrame parent)
    {
        super(parent, true);
        initComponents();
    }
    
    public boolean is_okay()    { return okay; }
    public String get_targ_path()
    {
        return CB_PATH.getEditor().getItem().toString();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        BT_OK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BT_ABORT = new javax.swing.JButton();
        CB_PATH = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zielpfad für Dateitransfer");

        BT_OK.setText("OK");
        BT_OK.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BT_OKActionPerformed(evt);
            }
        });

        jLabel1.setText("Zielpfad auf dem BettyMailArchiver");

        BT_ABORT.setText("Abbruch");
        BT_ABORT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BT_ABORTActionPerformed(evt);
            }
        });

        CB_PATH.setEditable(true);
        CB_PATH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "./update", "/etc", "." }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(BT_ABORT)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(BT_OK))
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(CB_PATH, 0, 160, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {BT_ABORT, BT_OK}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(CB_PATH, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(BT_OK)
                    .add(BT_ABORT))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_ABORTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_ABORTActionPerformed
    {//GEN-HEADEREND:event_BT_ABORTActionPerformed
// TODO Ihre Ereignisbehandlung hier einf�gen:
        okay = false;
        this.setVisible( false );
        this.dispose();
    }//GEN-LAST:event_BT_ABORTActionPerformed

    private void BT_OKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_OKActionPerformed
    {//GEN-HEADEREND:event_BT_OKActionPerformed
// TODO Ihre Ereignisbehandlung hier einf�gen:
        
        String trg_path = get_targ_path();
        if (trg_path == null || trg_path.length() == 0)
            return;
        
        
        okay = true;
        this.setVisible( false );
        this.dispose();
        
    }//GEN-LAST:event_BT_OKActionPerformed
    
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_ABORT;
    private javax.swing.JButton BT_OK;
    private javax.swing.JComboBox CB_PATH;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
