package dimm.home.hibernate;
// Generated 28.04.2009 17:09:44 by Hibernate Tools 3.2.1.GA



/**
 * DiskSpace generated by hbm2java
 */
public class DiskSpace  implements java.io.Serializable {


     private int id;
     private DiskArchive diskArchive;
     private String path;
     private String maxCapacity;

    public DiskSpace() {
    }

	
    public DiskSpace(int id, DiskArchive diskArchive, String path) {
        this.id = id;
        this.diskArchive = diskArchive;
        this.path = path;
    }
    public DiskSpace(int id, DiskArchive diskArchive, String path, String maxCapacity) {
       this.id = id;
       this.diskArchive = diskArchive;
       this.path = path;
       this.maxCapacity = maxCapacity;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public DiskArchive getDiskArchive() {
        return this.diskArchive;
    }
    
    public void setDiskArchive(DiskArchive diskArchive) {
        this.diskArchive = diskArchive;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public String getMaxCapacity() {
        return this.maxCapacity;
    }
    
    public void setMaxCapacity(String maxCapacity) {
        this.maxCapacity = maxCapacity;
    }




}


