package dimm.home.hibernate;
// Generated 08.07.2009 13:28:14 by Hibernate Tools 3.2.1.GA



/**
 * DiskSpace generated by hbm2java
 */
public class DiskSpace  implements java.io.Serializable {


     private int id;
     private DiskArchive diskArchive;
     private String path;
     private String maxCapacity;
     private String flags;
     private String status;

    public DiskSpace() {
    }

	
    public DiskSpace(int id, DiskArchive diskArchive, String path) {
        this.id = id;
        this.diskArchive = diskArchive;
        this.path = path;
    }
    public DiskSpace(int id, DiskArchive diskArchive, String path, String maxCapacity, String flags, String status) {
       this.id = id;
       this.diskArchive = diskArchive;
       this.path = path;
       this.maxCapacity = maxCapacity;
       this.flags = flags;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public DiskArchive getDiskArchive() {
        return this.diskArchive;
    }
    
    public void setDiskArchive(DiskArchive diskArchive) {
        this.diskArchive = diskArchive;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public String getMaxCapacity() {
        return this.maxCapacity;
    }
    
    public void setMaxCapacity(String maxCapacity) {
        this.maxCapacity = maxCapacity;
    }
    public String getFlags() {
        return this.flags;
    }
    
    public void setFlags(String flags) {
        this.flags = flags;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


