package dimm.home.hibernate;
// Generated 28.04.2009 17:09:44 by Hibernate Tools 3.2.1.GA



/**
 * Hotfolder generated by hbm2java
 */
public class Hotfolder  implements java.io.Serializable {


     private int id;
     private DiskArchive diskArchive;
     private Mandant mandant;
     private String userMailAdress;
     private String path;
     private String flags;

    public Hotfolder() {
    }

	
    public Hotfolder(int id, DiskArchive diskArchive, Mandant mandant, String userMailAdress, String path) {
        this.id = id;
        this.diskArchive = diskArchive;
        this.mandant = mandant;
        this.userMailAdress = userMailAdress;
        this.path = path;
    }
    public Hotfolder(int id, DiskArchive diskArchive, Mandant mandant, String userMailAdress, String path, String flags) {
       this.id = id;
       this.diskArchive = diskArchive;
       this.mandant = mandant;
       this.userMailAdress = userMailAdress;
       this.path = path;
       this.flags = flags;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public DiskArchive getDiskArchive() {
        return this.diskArchive;
    }
    
    public void setDiskArchive(DiskArchive diskArchive) {
        this.diskArchive = diskArchive;
    }
    public Mandant getMandant() {
        return this.mandant;
    }
    
    public void setMandant(Mandant mandant) {
        this.mandant = mandant;
    }
    public String getUserMailAdress() {
        return this.userMailAdress;
    }
    
    public void setUserMailAdress(String userMailAdress) {
        this.userMailAdress = userMailAdress;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public String getFlags() {
        return this.flags;
    }
    
    public void setFlags(String flags) {
        this.flags = flags;
    }




}


