package dimm.home.hibernate;
// Generated 29.05.2009 11:20:51 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hotfolder generated by hbm2java
 */
public class Hotfolder  implements java.io.Serializable {


     private int id;
     private DiskArchive diskArchive;
     private Mandant mandant;
     private String userMailAdress;
     private String path;
     private String flags;
     private Set<HotfolderExclude> hotfolderExcludes = new HashSet<HotfolderExclude>(0);

    public Hotfolder() {
    }

	
    public Hotfolder(int id, DiskArchive diskArchive, Mandant mandant, String userMailAdress, String path) {
        this.id = id;
        this.diskArchive = diskArchive;
        this.mandant = mandant;
        this.userMailAdress = userMailAdress;
        this.path = path;
    }
    public Hotfolder(int id, DiskArchive diskArchive, Mandant mandant, String userMailAdress, String path, String flags, Set<HotfolderExclude> hotfolderExcludes) {
       this.id = id;
       this.diskArchive = diskArchive;
       this.mandant = mandant;
       this.userMailAdress = userMailAdress;
       this.path = path;
       this.flags = flags;
       this.hotfolderExcludes = hotfolderExcludes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public DiskArchive getDiskArchive() {
        return this.diskArchive;
    }
    
    public void setDiskArchive(DiskArchive diskArchive) {
        this.diskArchive = diskArchive;
    }
    public Mandant getMandant() {
        return this.mandant;
    }
    
    public void setMandant(Mandant mandant) {
        this.mandant = mandant;
    }
    public String getUserMailAdress() {
        return this.userMailAdress;
    }
    
    public void setUserMailAdress(String userMailAdress) {
        this.userMailAdress = userMailAdress;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public String getFlags() {
        return this.flags;
    }
    
    public void setFlags(String flags) {
        this.flags = flags;
    }
    public Set<HotfolderExclude> getHotfolderExcludes() {
        return this.hotfolderExcludes;
    }
    
    public void setHotfolderExcludes(Set<HotfolderExclude> hotfolderExcludes) {
        this.hotfolderExcludes = hotfolderExcludes;
    }




}


