package dimm.home.hibernate;
// Generated 28.04.2009 17:09:44 by Hibernate Tools 3.2.1.GA



/**
 * ImapFetcher generated by hbm2java
 */
public class ImapFetcher  implements java.io.Serializable {


     private int id;
     private Mandant mandant;
     private String server;
     private Integer port;
     private int daId;
     private String flags;

    public ImapFetcher() {
    }

	
    public ImapFetcher(int id, Mandant mandant, String server, int daId) {
        this.id = id;
        this.mandant = mandant;
        this.server = server;
        this.daId = daId;
    }
    public ImapFetcher(int id, Mandant mandant, String server, Integer port, int daId, String flags) {
       this.id = id;
       this.mandant = mandant;
       this.server = server;
       this.port = port;
       this.daId = daId;
       this.flags = flags;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mandant getMandant() {
        return this.mandant;
    }
    
    public void setMandant(Mandant mandant) {
        this.mandant = mandant;
    }
    public String getServer() {
        return this.server;
    }
    
    public void setServer(String server) {
        this.server = server;
    }
    public Integer getPort() {
        return this.port;
    }
    
    public void setPort(Integer port) {
        this.port = port;
    }
    public int getDaId() {
        return this.daId;
    }
    
    public void setDaId(int daId) {
        this.daId = daId;
    }
    public String getFlags() {
        return this.flags;
    }
    
    public void setFlags(String flags) {
        this.flags = flags;
    }




}


