package dimm.home.hibernate;
// Generated 25.06.2009 14:19:53 by Hibernate Tools 3.2.1.GA



/**
 * MailHeader generated by hbm2java
 */
public class MailHeader  implements java.io.Serializable {


     private int id;
     private Mail mail;
     private MailHeaderVariable mailHeaderVariable;
     private String varValue;

    public MailHeader() {
    }

	
    public MailHeader(int id) {
        this.id = id;
    }
    public MailHeader(int id, Mail mail, MailHeaderVariable mailHeaderVariable, String varValue) {
       this.id = id;
       this.mail = mail;
       this.mailHeaderVariable = mailHeaderVariable;
       this.varValue = varValue;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mail getMail() {
        return this.mail;
    }
    
    public void setMail(Mail mail) {
        this.mail = mail;
    }
    public MailHeaderVariable getMailHeaderVariable() {
        return this.mailHeaderVariable;
    }
    
    public void setMailHeaderVariable(MailHeaderVariable mailHeaderVariable) {
        this.mailHeaderVariable = mailHeaderVariable;
    }
    public String getVarValue() {
        return this.varValue;
    }
    
    public void setVarValue(String varValue) {
        this.varValue = varValue;
    }




}


