package dimm.home.hibernate;
// Generated 25.06.2009 14:19:53 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MailRecipient generated by hbm2java
 */
public class MailRecipient  implements java.io.Serializable {


     private int id;
     private String mailAdress;
     private Set<MailRecipientLink> mailRecipientLinks = new HashSet<MailRecipientLink>(0);

    public MailRecipient() {
    }

	
    public MailRecipient(int id) {
        this.id = id;
    }
    public MailRecipient(int id, String mailAdress, Set<MailRecipientLink> mailRecipientLinks) {
       this.id = id;
       this.mailAdress = mailAdress;
       this.mailRecipientLinks = mailRecipientLinks;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMailAdress() {
        return this.mailAdress;
    }
    
    public void setMailAdress(String mailAdress) {
        this.mailAdress = mailAdress;
    }
    public Set<MailRecipientLink> getMailRecipientLinks() {
        return this.mailRecipientLinks;
    }
    
    public void setMailRecipientLinks(Set<MailRecipientLink> mailRecipientLinks) {
        this.mailRecipientLinks = mailRecipientLinks;
    }




}


