package dimm.home.hibernate;
// Generated 28.04.2009 17:09:44 by Hibernate Tools 3.2.1.GA



/**
 * Proxy generated by hbm2java
 */
public class Proxy  implements java.io.Serializable {


     private int id;
     private DiskArchive diskArchive;
     private Mandant mandant;
     private String localServer;
     private Integer localPort;
     private String remoteServer;
     private Integer remotePort;
     private String protokoll;
     private String flags;

    public Proxy() {
    }

	
    public Proxy(int id) {
        this.id = id;
    }
    public Proxy(int id, DiskArchive diskArchive, Mandant mandant, String inServer, Integer inPort, String outServer, Integer outPort, String type, String flags) {
       this.id = id;
       this.diskArchive = diskArchive;
       this.mandant = mandant;
       this.localServer = inServer;
       this.localPort = inPort;
       this.remoteServer = outServer;
       this.remotePort = outPort;
       this.protokoll = type;
       this.flags = flags;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public DiskArchive getDiskArchive() {
        return this.diskArchive;
    }
    
    public void setDiskArchive(DiskArchive diskArchive) {
        this.diskArchive = diskArchive;
    }
    public Mandant getMandant() {
        return this.mandant;
    }
    
    public void setMandant(Mandant mandant) {
        this.mandant = mandant;
    }
    public String getLocalServer() {
        return this.localServer;
    }
    
    public void setLocalServer(String inServer) {
        this.localServer = inServer;
    }
    public Integer getLocalPort() {
        return this.localPort;
    }
    
    public void setLocalPort(Integer inPort) {
        this.localPort = inPort;
    }
    public String getRemoteServer() {
        return this.remoteServer;
    }
    
    public void setRemoteServer(String outServer) {
        this.remoteServer = outServer;
    }
    public Integer getRemotePort() {
        return this.remotePort;
    }
    
    public void setRemotePort(Integer outPort) {
        this.remotePort = outPort;
    }
    public String getProtokoll() {
        return this.protokoll;
    }
    
    public void setProtokoll(String protokoll) {
        this.protokoll = protokoll;
    }
    public String getFlags() {
        return this.flags;
    }
    
    public void setFlags(String flags) {
        this.flags = flags;
    }




}


