package dimm.home.hibernate;
// Generated 29.05.2009 11:20:51 by Hibernate Tools 3.2.1.GA



/**
 * Proxy generated by hbm2java
 */
public class Proxy  implements java.io.Serializable {


     private int id;
     private DiskArchive diskArchive;
     private Mandant mandant;
     private String localServer;
     private Integer localPort;
     private String remoteServer;
     private Integer remotePort;
     private String type;
     private String flags;

    public Proxy() {
    }

	
    public Proxy(int id) {
        this.id = id;
    }
    public Proxy(int id, DiskArchive diskArchive, Mandant mandant, String localServer, Integer localPort, String remoteServer, Integer remotePort, String type, String flags) {
       this.id = id;
       this.diskArchive = diskArchive;
       this.mandant = mandant;
       this.localServer = localServer;
       this.localPort = localPort;
       this.remoteServer = remoteServer;
       this.remotePort = remotePort;
       this.type = type;
       this.flags = flags;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public DiskArchive getDiskArchive() {
        return this.diskArchive;
    }
    
    public void setDiskArchive(DiskArchive diskArchive) {
        this.diskArchive = diskArchive;
    }
    public Mandant getMandant() {
        return this.mandant;
    }
    
    public void setMandant(Mandant mandant) {
        this.mandant = mandant;
    }
    public String getLocalServer() {
        return this.localServer;
    }
    
    public void setLocalServer(String localServer) {
        this.localServer = localServer;
    }
    public Integer getLocalPort() {
        return this.localPort;
    }
    
    public void setLocalPort(Integer localPort) {
        this.localPort = localPort;
    }
    public String getRemoteServer() {
        return this.remoteServer;
    }
    
    public void setRemoteServer(String remoteServer) {
        this.remoteServer = remoteServer;
    }
    public Integer getRemotePort() {
        return this.remotePort;
    }
    
    public void setRemotePort(Integer remotePort) {
        this.remotePort = remotePort;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getFlags() {
        return this.flags;
    }
    
    public void setFlags(String flags) {
        this.flags = flags;
    }




}


